# Generated by Django 4.2.30 on 2026-05-09 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=100, unique=True)),
                ('is_covered', models.BooleanField(default=False, help_text='True if we deliver here')),
                ('delivery_days', models.IntegerField(default=3, help_text='Estimated delivery time in working days')),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=0, help_text='Delivery fee in UGX. 0 = free delivery', max_digits=10)),
                ('free_above', models.DecimalField(decimal_places=2, default=200000, help_text='Orders above this amount get free delivery', max_digits=12)),
                ('notes', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['district'],
            },
        ),
    ]
