# Generated by Django 4.2.30 on 2026-05-09 17:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(help_text='URL-safe name: "home-living" not "Home & Living"', unique=True)),
                ('icon', models.CharField(blank=True, help_text='Emoji icon: 📱 🍳 ❄️', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, help_text='Parent category, if this is a sub-category', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='products.category')),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(help_text='URL: /product/samsung-43-qled-tv', unique=True)),
                ('description', models.TextField(blank=True)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('promo_price', models.DecimalField(blank=True, decimal_places=2, help_text='Set automatically when a promotion activates', max_digits=12, null=True)),
                ('on_promo', models.BooleanField(default=False, help_text='True when an active promotion is applying a discount')),
                ('stock_qty', models.IntegerField(default=0, help_text='Current stock. 0 = out of stock.')),
                ('attributes', models.JSONField(default=dict, help_text='Product specifications as key-value pairs')),
                ('images', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.category')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='users.vendorprofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['category'], name='products_pr_categor_9edb3d_idx'), models.Index(fields=['brand'], name='products_pr_brand_4bfaa4_idx'), models.Index(fields=['on_promo'], name='products_pr_on_prom_562c12_idx'), models.Index(fields=['is_active', 'stock_qty'], name='products_pr_is_acti_5e89e4_idx')],
            },
        ),
    ]
