# Generated by Django 4.2.30 on 2026-05-09 17:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('promo_type', models.CharField(choices=[('flash_sale', 'Flash Sale'), ('clearance', 'Clearance'), ('bundle', 'Bundle Deal'), ('brand_week', 'Brand Week')], max_length=30)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('live', 'Live'), ('paused', 'Paused'), ('ended', 'Ended')], default='draft', max_length=20)),
                ('discount_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('applies_to', models.CharField(choices=[('all', 'All Products'), ('category', 'Specific Category'), ('brand', 'Specific Brand'), ('selected_skus', 'Selected Products Only')], default='all', max_length=30)),
                ('category_slug', models.CharField(blank=True, max_length=100)),
                ('brand_name', models.CharField(blank=True, max_length=100)),
                ('min_qty', models.IntegerField(default=1, help_text='Minimum quantity for bundle deals')),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField(blank=True, help_text='Leave blank = runs until stock out', null=True)),
                ('auto_end_on_stockout', models.BooleanField(default=False)),
                ('target_orders', models.IntegerField(blank=True, null=True)),
                ('orders_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
